version: "3.1"

networks:
  ghost_network:
services:
  ghost:
    image: ghost:3-alpine
    container_name: ghost
    restart: always
    ports:
      - 8080:2368
    environment:
      url: http://hugolausenazpire.fr
