version: "3"

networks:
  ghost_network:
services:
  ghost:
    image: ghost:3-alpine
    container_name: ghost
    restart: always
    ports:
      - 2368:2368
    depends_on:
      - mariadb-ghost
    environment:
      url: "http://${DOMAIN_NAME}"
      VIRTUAL_HOST: "${DOMAIN_NAME}"
      LETSENCRYPT_HOST: "${DOMAIN_NAME}"
      LETSENCRYPT_EMAIL: "${EMAIL}"
      database__client: mysql
      database__connection__host: mariadb-ghost
      database__connection__user: ${MYSQLUSER}
      database__connection__password: ${MYSQLPASSWORD}
      database__connection__database: ${MYSQLDB}

  mariadb-ghost:
    container_name: mariadb-ghost
    image: mariadb:focal
    restart: unless-stopped
    volumes:
      - datasqlghost:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: '1'
      MYSQL_USER: ${MYSQLUSER}
      MYSQL_PASSWORD: ${MYSQLPASSWORD}
      MYSQL_DATABASE: ${MYSQLDB}

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - dhparam:/etc/nginx/dhparam
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    restart: always
    volumes:
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs
      - dhparam:/etc/nginx/dhparam:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      DEFAULT_EMAIL: "${EMAIL}"

volumes:
    conf:
    vhost:
    html:
    certs:
    dhparam:
