version: "3.1"

networks:
  ghost_network:
services:
  ghost:
    image: ghost:3-alpine
    container_name: ghost
    restart: always
    ports:
      - 2368:2368
    environment:
      url: https://hugolausenazpire.fr
      VIRTUAL_HOST: hugolausenazpire.fr
      LETSENCRYPT_HOST: hugolausenazpire.fr
      LETSENCRYPT_EMAIL: pro@hugolausenazpire.fr

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - certs:/etc/nginx/certs
      - vhost.d:/etc/nginx/vhost.d
      - html:/etc/nginx/html
      - dhparam:/etc/nginx/dhparam

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    restart: always
    volumes:
      - certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - vhost.d:/etc/nginx/vhost.d
      - html:/etc/nginx/html
      - dhparam:/etc/nginx/dhparam
    environment:
      DEFAULT_EMAIL: pro@hugolausenazpire.fr

volumes:
  certs:
  vhost:
  html:
  dhparam:
