version: '3'

networks:
  ghost_network:
services:
  traefik:
    container_name: traefik
    image: traefik:picodon
    restart: unless-stopped
    ports:
      - 2368:2368
    depends_on:
      - mariadb-ghost
    environment:
      url: "http://${DOMAIN_NAME}"
      VIRTUAL_HOST: "${DOMAIN_NAME}"
      LETSENCRYPT_HOST: "${DOMAIN_NAME}"
      LETSENCRYPT_EMAIL: "${EMAIL}"
      database__client: mysql
      database__connection__host: mariadb-ghost
      database__connection__user: ${MYSQLUSER}
      database__connection__password: ${MYSQLPASSWORD}
      database__connection__database: ${MYSQLDB}

  mariadb-ghost:
    container_name: mariadb-ghost
    image: mariadb:focal
    restart: unless-stopped
    volumes:
      - datasqlghost:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: '1'
      MYSQL_USER: ${MYSQLUSER}
      MYSQL_PASSWORD: ${MYSQLPASSWORD}
      MYSQL_DATABASE: ${MYSQLDB}

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./conf/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./conf/traefikdynamic:/traefikdynamic:ro
      - ./logs/traefik.log:/etc/traefik/applog.log
      - ./conf/acme.json:/acme.json

  sqlghost:
    container_name: mariadb-ghost
    image: mariadb:bionic
    restart: unless-stopped
    volumes:
      - datasqlghost:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'toor'
      MYSQL_USER: ${MYSQLUSER}
      MYSQL_PASSWORD: ${MYSQLPWD}
      MYSQL_DATABASE: ${MYSQLDB}

  ghost:
    container_name: cmsghost
    image: ghost:3
    restart: unless-stopped
    volumes:
      - ./ghost/content/:/var/lib/ghost/content
      - ./conf/config.production.json:/var/lib/ghost/config.production.json:ro
    depends_on:
      - sqlghost
    labels:
      traefik.enable: true
      traefik.http.routers.ghost-https.entrypoints: websecure
      traefik.http.routers.ghost-https.rule: Host(`ghost.czs.local`)
      traefik.http.routers.ghost-https.middlewares: compression@file, security@file
      traefik.http.routers.ghost-https.tls: true
      traefik.http.routers.ghost-https.tls.certresolver: "letsencrypt"

volumes:
  datasqlghost:
  dataghost:
