version: '3.6'

networks:
  ghost-network:

services:
  traefik:
    container_name: traefik
    image: traefik:picodon
    restart: unless-stopped
    ports:
      - 2368:2368
    depends_on:
      - mariadb-ghost
    environment:
      url: "http://${DOMAIN_NAME}"
      VIRTUAL_HOST: "${DOMAIN_NAME}"
      LETSENCRYPT_HOST: "${DOMAIN_NAME}"
      LETSENCRYPT_EMAIL: "${EMAIL}"
      database__client: mysql
      database__connection__host: mariadb-ghost
      database__connection__user: ${MYSQLUSER}
      database__connection__password: ${MYSQLPASSWORD}
      database__connection__database: ${MYSQLDB}

  mariadb-ghost:
    container_name: mariadb-ghost
    image: mariadb:focal
    restart: unless-stopped
    volumes:
      - datasqlghost:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: '1'
      MYSQL_USER: ${MYSQLUSER}
      MYSQL_PASSWORD: ${MYSQLPASSWORD}
      MYSQL_DATABASE: ${MYSQLDB}

  mariadb-ghost:
    container_name: mariadb-ghost
    image: mariadb:focal
    restart: unless-stopped
    volumes:
      - datasqlghost:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: '1'
      MYSQL_USER: ${MYSQLUSER}
      MYSQL_PASSWORD: ${MYSQLPASSWORD}
      MYSQL_DATABASE: ${MYSQLDB}

  ghost:
    container_name: ghost
    image: ghost:3
    restart: unless-stopped
    volumes:
      - ./ghost/content/:/var/lib/ghost/content
      - ./conf/config.production.json:/var/lib/ghost/config.production.json:ro
    depends_on:
      - mariadb-ghost
    labels:
      traefik.enable: true
      traefik.http.routers.ghost-https.entrypoints: websecure
      traefik.http.routers.ghost-https.rule: Host(`YOUR_DOMAIN`)
      traefik.http.routers.ghost-https.middlewares: compression@file, security@file
      traefik.http.routers.ghost-https.tls: true
      traefik.http.routers.ghost-https.tls.certresolver: "letsencrypt"
    environment:
      # see https://docs.ghost.org/docs/config#section-running-ghost-with-config-env-variables
      database__client: mysql
      database__connection__host: mariadb-ghost
      database__connection__user: ${MYSQLUSER}
      database__connection__password: ${MYSQLPASSWORD}
      database__connection__database: ${MYSQLDB}
      # this url value is just an example, and is likely wrong for your environment!
      url: http://YOUR_DOMAIN

volumes:
  datasqlghost:
  dataghost:
